### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ozymandog** [itsneyoa/fragrunning-bot#3]
Is there a whitelist/blacklist system for the bot?

**Comment by itsneyoa** [comment]
Yep! Check out the [config wiki page](https://github.com/itsneyoa/fragrunning-bot/wiki/Configuration#fragrunning-options).

**Comment by Ozymandog** [comment]
> Yep! Check out the [config wiki page](https://github.com/itsneyoa/fragrunning-bot/wiki/Configuration#fragrunning-options).

ooooh woah thats really cool, thanks!

**Comment by Ozymandog** [comment]
can I run this fragbot code on a minecraft account that's running senither's bridge bot code?

**Comment by itsneyoa** [comment]
You can't right now but there's no reason why they wouldn't be able to run off the same bot - it would just require a bit of work to combine them into one app. I haven't played in a long time however it's my understanding that you can no longer party accounts who are in limbo, so the bot would need somewhere else to afk if being used for fragruns.
