### ISSUE TITLE
another question

### ISSUE THREAD

**Issue by Ozymandog** [itsneyoa/fragrunning-bot#4]
So is it possible to make it so it doesnt afk in limbo and it afks on the private island so I can have the account use rabbit pet to buff farming minions and if it disconnects it just goes back?

**Comment by ghost** [comment]
1. That'll get you banned (Likely, at least) for profile boosting.
2. If you really want something like that, just change the code.

**Comment by itsneyoa** [comment]
Hi! Sorry for the late response, I've only just seen this issue open. If you want to add this all you'd need to do is replace the following in `ChatHandler.js`:
```js
  if (this.isLobbyJoinMessage(message)) {
    this.app.log.client('Sending Minecraft client to limbo')
    return this.bot.chat('/ac §') // This would probably chat something like '/play sb'
  }

// Add more checks to run '/is' or '/visit <player>' and interact with the gui on the 'You are playing on profile ...' or 'Welcome to Hypixel Skyblock' chat messages
```

Hope this helps and Merry Christmas!

**Comment by itsneyoa** [comment]
> 1. That'll get you banned (Likely, at least) for profile boosting.

As for this the [rules](https://hypixel.net/skyblock-rules/#rule-1-section-3) aren't explicit, so its easy to argue both sides of the argument. That being said I'm not an admin and have no easy way of contacting an admin to ask, so I would call it as use at your own risk.

> 2. If you really want something like that, just change the code.

No need to be rude. They've asked for help and I'm more than happy to point them in the right direction.
