### ISSUE TITLE
"Guild" mode doesnt work 

### ISSUE THREAD

**Issue by Soapdevs** [itsneyoa/fragrunning-bot#5]
hey there, the "guild" frag running mode doesn't work
when you try to use it, it simply says "Error getting players from {guild} - Error 400" returning to public mode

dunno how to fix this so if anyone can preciate it

**Comment by Soapdevs** [comment]
I guess this repo is no longer maintained so I am closing this lmao

**Comment by itsneyoa** [comment]
Hey! Sorry, I must have missed the first notification for the issue so haven't seen it before. You're right that I don't actively maintain this due to quitting a while ago, but when I get chance I'll have a look for you!

**Comment by Soapdevs** [comment]
Alright thanks!

**Comment by itsneyoa** [comment]
Fixed the axios error 400 👍
